### ISSUE TITLE
Exception: The input[0] need 4dims input, but 3dims input buffer feed

### ISSUE THREAD

**Issue by RobbyGit** [thanhtantran/rknn-single-thread-3566#1]
Seem to error with the following:

 Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/orangepi/.local/lib/python3.10/site-packages/rknnlite/api/rknn_lite.py", line 200, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1067, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

done
Traceback (most recent call last):
  File "/home/orangepi/rknn-single-thread-3566/camera.py", line 275, in <module>
    input0_data = outputs[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by sergiimokin** [comment]
Hello.
I am using Orange PI 5 Armbian OS.
python 3.11

I have the same problem. Did you solve it?

I have a few thoughts on the possible problem.

1. Other repositories. The repository https://github.com/rockchip-linux/rknn-toolkit2 says it is not supported, so I cloned this repository https://github.com/airockchip/rknn-toolkit2/

2. Another OS. I am using Armbian OS instead of Ubuntu as required in the documentation. Although I think this is not a problem.

What can you recommend ways to solve the problem?

I provide the error log:

E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/opi/.venv/lib/python3.11/site-packages/rknnlite/api/rknn_lite.py", line 201, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1082, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

Traceback (most recent call last):
  File "/home/opi/ws/rknn-multi-threaded-3588/main.py", line 36, in <module>
    frame, flag = pool.get()
                  ^^^^^^^^^^
  File "/home/opi/ws/rknn-multi-threaded-3588/rknnpool.py", line 54, in get
    return fut.result(), True
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
E Catch exception when setting inputs.
           ^^^^^^^^^^^^^^^^^^^
E Traceback (most recent call last):
  File "/home/opi/.venv/lib/python3.11/site-packages/rknnlite/api/rknn_lite.py", line 201, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1082, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opi/ws/rknn-multi-threaded-3588/func.py", line 206, in myFunc
    input0_data = outputs[0].reshape([3, -1]+list(outputs[0].shape[-2:]))
                  ~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by mruck03** [comment]
Hi any progress on this? I am running into the same issues with the Orange Pi 5B

**Comment by dlavrantonis** [comment]
fell into the same issue today. Looks like the inference function in the rknnrt library has recently been changed and expects a 4 dim array (a batch of images to infer them at once? no idea)
in any case, e.g. do this in where the .inference is called and it will work (=use numpy to expand the array)

```
-            output = rknn_lite.inference(inputs=[input])
+            output = rknn_lite.inference(inputs=[np.expand_dims(input, axis=0)])
```

**Comment by ahillelt** [comment]
Expanding worked for me, thanks for the suggestion. I do need to verify everything is in order. the RockChip repo is pretty bare and inconsistent, sometimes includes overly complicated code too for no reason (ha) or you know a model zoo that only has x86/x64 examples for using rknn, not rknnlite. Amazing. 

Thankful for this community!
